FROM docker.io/clojure:temurin-25-tools-deps-trixie
#RUN apk add libgcc libstdc++ ripgrep # if this was alpine
RUN apt update && apt install -y ripgrep curl ca-certificates  nodejs npm

# Claude Only for development
RUN curl -fsSL https://claude.ai/install.sh | bash -s latest
#RUN npm install -g @anthropic-ai/claude-code

WORKDIR /app
